### ISSUE TITLE
cannot login, fail: challenge_required

### ISSUE THREAD

**Issue by hadifarnoud** [falzm/instafeed#2]
there is no way to pass this error. I keep my instagram open but it fails before the confirmation screen comes up on instagram.
![IMG_3B5E8915591A-1](https://user-images.githubusercontent.com/589808/62036967-1eef6a00-b208-11e9-87c3-e5eed0e636d7.jpeg)

```
Unable to import Instagram configuration: open /Users/hadifarnoud/.instafeed: no such file or directory
Attempting new login
error: unable to initialize Instagram client: fail: challenge_required (checkpoint_challenge_required)
```

**Comment by hadifarnoud** [comment]
@falzm looks like this is fixed in newest version of goinsta https://github.com/ahmdrz/goinsta/tree/2.4.3

please update

**Comment by falzm** [comment]
Thank you for reporting this issue. I'll upgrade as soon as the upstream repository fixes its latest tag: https://github.com/ahmdrz/goinsta/issues/262

**Comment by falzm** [comment]
I have this error, not sure if I have something wrong [in my go.mod](https://github.com/falzm/instafeed/blob/master/go.mod):

```console
$ go get -u github.com/ahmdrz/goinsta/v2
go: github.com/ahmdrz/goinsta/v2@v2.4.3: go.mod has non-.../v2 module path "github.com/ahmdrz/goinsta" (and .../v2/go.mod does not exist) at revision v2.4.3
go get: error loading module requirements
```

**Comment by falzm** [comment]
@hadifarnoud i've published a [pre-release of version 0.3.1](https://github.com/falzm/instafeed/releases/tag/v0.3.1-rc1) that should fix the issue (depending on the upstream fix in goinsta), can you try it out and tell me if it's better now?

**Comment by hadifarnoud** [comment]
now I have a new issue. Facebook sends me a login code via SMS and it fails
```
Unable to import Instagram configuration: open /Users/hadifarnoud/.instafeed: no such file or directory
Attempting new login
error: unable to initialize Instagram client: fail:  ()
```

**Comment by hadifarnoud** [comment]
I was able to login successfully with another account on the second try

**Comment by falzm** [comment]
This second error worries me a bit, can you confirm it's working fine for you? You mentioned that it still doesn't work with your first account but it works with another account, can you please tell me if the current version (0.3.0) works as-is with your second account?

**Comment by hadifarnoud** [comment]
@falzm it does not work on my first account as it sends a code via SMS to my mobile. I'm not sure how I can check the version number tbh. there is no paramtere for that

**Comment by falzm** [comment]
I've pushed a new version 0.3.1-rc2 featuring a `-v` flag that can be used to show the current version: https://github.com/falzm/instafeed/releases/tag/v0.3.1-rc2

**Comment by falzm** [comment]
@hadifarnoud can you confirm that the changes in this branch fix your problem? This way I can issue a proper release.
